### PR TITLE
Add feature to force update all modules in non-interactive mode.

### PR DESCRIPTION
**Pull request by koykov**

### CODE REVIEW

**Comment by koykov** [comment]
@oligot Your tool is amazing, but I need an extra feature to update all modules in my project without choosing them.
So, I added new flag **-f** that forces update of the modules.

**Comment by oligot** [comment]
Hi,

This is a really great idea, thanks for your contribution.

**Comment by oligot** [comment]
Landed in version [v0.5.0](https://github.com/oligot/go-mod-upgrade/releases/tag/v0.5.0)

We now use the module [urfave/cli](https://github.com/urfave/cli) to parse the command line (instead of the built-in flag module).
This comes with a lot of useful features, as explained in the [manual](https://github.com/urfave/cli/blob/master/docs/v2/manual.md).

go-mod-upgrade-v0 5 0

**Comment by koykov** [comment]
Wow! I see it supports bash completion. Thanks for notice!
I'll use in in my projects too.

**Pull request merged**
