### PR TITLE
Cli flag tidy vendor

### PR DESCRIPTION
**Pull request by koykov**
Hello @oligot 
I use you great tool every time when I need to update my projects dependencies and it works perfect.
But I must run manually `go mod tidy/vendor` after every use and it's inconvenient for me.
So I added two new flags to the tool:
- --tidy (-t) to run `go mod tidy`
- --vendor (-n since -v already used for verbose flag) to run `go mod verbose`
Hope you will find these changes useful.

### CODE REVIEW

**Comment by oligot** [comment]
Hi,
Just so I understand what you are trying to do: why do you need to run those commands afterwards ? What files do they change ?

**Comment by koykov** [comment]
> Hi,
> Just so I understand what you are trying to do: why do you need to run those commands afterwards ? What files do they change ?

I use vendoring in my projects. When I run `go-mod-update` it just changes go.mod file. To get updates in vendor directory I need run two commands consecitive:
- `go mod tidy` to update go.sum and make checks
- `go mod vendor` to copy updated modules to vendor directory

As I mentioned, now I must run those commands manually and want to automatize that process.

In a word, I want to run `go-mod-update --tidy --vendor` instead of chain of commands:
- `go-mod-update`
- `go mod tidy`
- `go mod vendor`

**Comment by oligot** [comment]
Would an alias like suggested in https://github.com/oligot/go-mod-upgrade/pull/13#issuecomment-804050462 work for you ?

```bash
alias goupgradetidyvendor = 'go-mod-upgrade && go mod tidy && go mod vendor'
```

Then instead of using
```bash
> go-mod-upgrade
```
you would use
```bash
> goupgradetidyvendor
```

**Comment by koykov** [comment]
Looks like good solution. Thank you for review!

**Pull request closed without merging**
