### PR TITLE
Add possibility to git commit update

### PR DESCRIPTION
**Pull request by rubda**
Really appreciate this tool! One thing I've personally have been missing is to commit each update. I use the following code changes in my own setup, but figured others might be interested as well. If not, feel free to close this PR.

EDIT: opted to use the var `gitCommit` to avoid collision with the current global `commit` var.

### CODE REVIEW

**Comment by oligot** [comment]
Hi,

Thanks for your contribution.

For these kind of changes, I tend to use a shell (bash/zsh) alias or a small bash script, as other might have different commit messages (otherwise, we would have to introduce another CLI args to specify the commit message)
```bash
alias upgradedeps = 'go-mod-upgrade && git add go.mod go.sum && git commit -m "chore(deps): bump deps"'
```

Then instead of using
```bash
> go-mod-upgrade
```
you would use
```bash
> upgradedeps
```

**Comment by rubda** [comment]
Hey, thanks for the review @oligot.

> For these kind of changes, I tend to use a shell (bash/zsh) alias or a small bash script, as other might have different commit messages (otherwise, we would have to introduce another CLI args to specify the commit message)

Sure, I understand that people might have different commit preferences.

> alias upgradedeps = 'go-mod-upgrade && git add go.mod go.sum && git commit -m "chore(deps): bump deps"'

Wouldn't this bundle all deps upgraded into one single commit? The desired behavior I want is that every dep that is upgraded is contained to a single commit. This makes it easier to revert a single update gone bad, as well as letting any reviewer know what dep is getting upgraded (from version X to version Y) by simply looking at the commit message.

**Comment by oligot** [comment]
Yes, this would bundle all deps upgraded into a single commit.

I assume it depends on the type of projects, but upgrading dependencies is not always as easy as bumping the version in the go.mod file and committing the changes.
As soon as you have some (unit/functional/E2E) testing in place, you would probably run those tests and only commit when the tests passes.
You could also decide to group multiple upgrades together, as there are tightly related (ex: a web framework with some external middlewares): in this case, having a single commit with multiple upgraded deps is more appropriate.

go-mod-upgrade is firstly an interactive tool, where you choose the number of dependencies you want to upgrade (one or multiple).
I'm not sure it's the right tool for the kind of automation you are trying to do: maybe some parts could be extracted into another dedicated tool that is tailored to your needs (which is, AFAIK, to change and commit single dependencies).

**Comment by rubda** [comment]
Yeah, each project has its own specific needs and `go-mod-upgrade` is for sure an interactive tool (even though there is a `-f` flag nowadays).

I don't see how this PR would change that, the commit flag is optional and defaults to false. But yeah, I understand that this might not align perfectly with what was meant for this tool. Feel free to close this PR, thanks for having a look!

**Comment by oligot** [comment]
I think I found a way to include your requirements (with a slightly different approach, but with same result).
I'll update this conversation when I have working prototype (so that you can try it on your side).

**Comment by oligot** [comment]
And here is the proposed PR: #14 
@rubda can you take a look at it and see if it works for you ?

**Comment by rubda** [comment]
It certainly works for me, closing this PR in favour of yours 🙌

**Pull request closed without merging**
